package com.kxkj.wxpublic.dao.mapper;

import com.kxkj.wxpublic.dao.model.ArticleDo;
import com.kxkj.wxpublic.dao.model.ArticleDoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ArticleDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_article
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int countByExample(ArticleDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_article
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int deleteByExample(ArticleDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_article
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_article
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int insert(ArticleDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_article
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int insertSelective(ArticleDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_article
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    List<ArticleDo> selectByExampleWithBLOBs(ArticleDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_article
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    List<ArticleDo> selectByExample(ArticleDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_article
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    ArticleDo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_article
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int updateByExampleSelective(@Param("record") ArticleDo record, @Param("example") ArticleDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_article
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") ArticleDo record, @Param("example") ArticleDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_article
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int updateByExample(@Param("record") ArticleDo record, @Param("example") ArticleDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_article
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int updateByPrimaryKeySelective(ArticleDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_article
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(ArticleDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_article
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int updateByPrimaryKey(ArticleDo record);
}