package com.kxkj.wxpublic.dao.mapper;

import com.kxkj.wxpublic.dao.model.ImgDo;
import com.kxkj.wxpublic.dao.model.ImgDoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ImgDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_img
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int countByExample(ImgDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_img
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int deleteByExample(ImgDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_img
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_img
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int insert(ImgDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_img
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int insertSelective(ImgDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_img
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    List<ImgDo> selectByExample(ImgDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_img
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    ImgDo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_img
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int updateByExampleSelective(@Param("record") ImgDo record, @Param("example") ImgDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_img
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int updateByExample(@Param("record") ImgDo record, @Param("example") ImgDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_img
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int updateByPrimaryKeySelective(ImgDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_img
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int updateByPrimaryKey(ImgDo record);
}