package com.kxkj.wxpublic.dao.mapper;

import com.kxkj.wxpublic.dao.model.TagDo;
import com.kxkj.wxpublic.dao.model.TagDoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TagDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_tag
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int countByExample(TagDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_tag
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int deleteByExample(TagDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_tag
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_tag
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int insert(TagDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_tag
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int insertSelective(TagDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_tag
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    List<TagDo> selectByExample(TagDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_tag
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    TagDo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_tag
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int updateByExampleSelective(@Param("record") TagDo record, @Param("example") TagDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_tag
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int updateByExample(@Param("record") TagDo record, @Param("example") TagDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_tag
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int updateByPrimaryKeySelective(TagDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_tag
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int updateByPrimaryKey(TagDo record);
}