package com.kxkj.wxpublic.dao.mapper;

import com.kxkj.wxpublic.dao.model.ThirdPlatformInfoDo;
import com.kxkj.wxpublic.dao.model.ThirdPlatformInfoDoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ThirdPlatformInfoDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_third_platform_info
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int countByExample(ThirdPlatformInfoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_third_platform_info
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int deleteByExample(ThirdPlatformInfoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_third_platform_info
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_third_platform_info
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int insert(ThirdPlatformInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_third_platform_info
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int insertSelective(ThirdPlatformInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_third_platform_info
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    List<ThirdPlatformInfoDo> selectByExample(ThirdPlatformInfoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_third_platform_info
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    ThirdPlatformInfoDo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_third_platform_info
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int updateByExampleSelective(@Param("record") ThirdPlatformInfoDo record, @Param("example") ThirdPlatformInfoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_third_platform_info
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int updateByExample(@Param("record") ThirdPlatformInfoDo record, @Param("example") ThirdPlatformInfoDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_third_platform_info
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int updateByPrimaryKeySelective(ThirdPlatformInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_third_platform_info
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    int updateByPrimaryKey(ThirdPlatformInfoDo record);
}