package com.kxkj.wxpublic.dao.model;

import java.util.Date;

public class HallDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_hall.id
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_hall.name
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_hall.type
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_hall.article_id
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private Long articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_hall.user_id
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_hall.is_private
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private Integer isPrivate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_hall.gmt_create
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_hall.gmt_modified
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_hall.creator
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_hall.state
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_hall.id
     *
     * @return the value of ml_hall.id
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_hall.id
     *
     * @param id the value for ml_hall.id
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_hall.name
     *
     * @return the value of ml_hall.name
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_hall.name
     *
     * @param name the value for ml_hall.name
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_hall.type
     *
     * @return the value of ml_hall.type
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_hall.type
     *
     * @param type the value for ml_hall.type
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_hall.article_id
     *
     * @return the value of ml_hall.article_id
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_hall.article_id
     *
     * @param articleId the value for ml_hall.article_id
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_hall.user_id
     *
     * @return the value of ml_hall.user_id
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_hall.user_id
     *
     * @param userId the value for ml_hall.user_id
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_hall.is_private
     *
     * @return the value of ml_hall.is_private
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public Integer getIsPrivate() {
        return isPrivate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_hall.is_private
     *
     * @param isPrivate the value for ml_hall.is_private
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setIsPrivate(Integer isPrivate) {
        this.isPrivate = isPrivate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_hall.gmt_create
     *
     * @return the value of ml_hall.gmt_create
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_hall.gmt_create
     *
     * @param gmtCreate the value for ml_hall.gmt_create
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_hall.gmt_modified
     *
     * @return the value of ml_hall.gmt_modified
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_hall.gmt_modified
     *
     * @param gmtModified the value for ml_hall.gmt_modified
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_hall.creator
     *
     * @return the value of ml_hall.creator
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_hall.creator
     *
     * @param creator the value for ml_hall.creator
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_hall.state
     *
     * @return the value of ml_hall.state
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_hall.state
     *
     * @param state the value for ml_hall.state
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}