package com.kxkj.wxpublic.dao.model;

import java.util.Date;

public class ShareHistDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_share_hist.id
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_share_hist.from
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private Long from;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_share_hist.to
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private Long to;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_share_hist.article_id
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private Long articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_share_hist.gmt_create
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_share_hist.gmt_modified
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_share_hist.creator
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_share_hist.state
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_share_hist.id
     *
     * @return the value of ml_share_hist.id
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_share_hist.id
     *
     * @param id the value for ml_share_hist.id
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_share_hist.from
     *
     * @return the value of ml_share_hist.from
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public Long getFrom() {
        return from;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_share_hist.from
     *
     * @param from the value for ml_share_hist.from
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setFrom(Long from) {
        this.from = from;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_share_hist.to
     *
     * @return the value of ml_share_hist.to
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public Long getTo() {
        return to;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_share_hist.to
     *
     * @param to the value for ml_share_hist.to
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setTo(Long to) {
        this.to = to;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_share_hist.article_id
     *
     * @return the value of ml_share_hist.article_id
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_share_hist.article_id
     *
     * @param articleId the value for ml_share_hist.article_id
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_share_hist.gmt_create
     *
     * @return the value of ml_share_hist.gmt_create
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_share_hist.gmt_create
     *
     * @param gmtCreate the value for ml_share_hist.gmt_create
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_share_hist.gmt_modified
     *
     * @return the value of ml_share_hist.gmt_modified
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_share_hist.gmt_modified
     *
     * @param gmtModified the value for ml_share_hist.gmt_modified
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_share_hist.creator
     *
     * @return the value of ml_share_hist.creator
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_share_hist.creator
     *
     * @param creator the value for ml_share_hist.creator
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_share_hist.state
     *
     * @return the value of ml_share_hist.state
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_share_hist.state
     *
     * @param state the value for ml_share_hist.state
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}