package com.kxkj.wxpublic.dao.model;

import java.util.Date;

public class ThirdPlatformInfoDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_third_platform_info.id
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_third_platform_info.type
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_third_platform_info.open_id
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_third_platform_info.user_id
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_third_platform_info.gmt_create
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_third_platform_info.gmt_modified
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_third_platform_info.creator
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_third_platform_info.state
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_third_platform_info.id
     *
     * @return the value of ml_third_platform_info.id
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_third_platform_info.id
     *
     * @param id the value for ml_third_platform_info.id
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_third_platform_info.type
     *
     * @return the value of ml_third_platform_info.type
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_third_platform_info.type
     *
     * @param type the value for ml_third_platform_info.type
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_third_platform_info.open_id
     *
     * @return the value of ml_third_platform_info.open_id
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_third_platform_info.open_id
     *
     * @param openId the value for ml_third_platform_info.open_id
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_third_platform_info.user_id
     *
     * @return the value of ml_third_platform_info.user_id
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_third_platform_info.user_id
     *
     * @param userId the value for ml_third_platform_info.user_id
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_third_platform_info.gmt_create
     *
     * @return the value of ml_third_platform_info.gmt_create
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_third_platform_info.gmt_create
     *
     * @param gmtCreate the value for ml_third_platform_info.gmt_create
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_third_platform_info.gmt_modified
     *
     * @return the value of ml_third_platform_info.gmt_modified
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_third_platform_info.gmt_modified
     *
     * @param gmtModified the value for ml_third_platform_info.gmt_modified
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_third_platform_info.creator
     *
     * @return the value of ml_third_platform_info.creator
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_third_platform_info.creator
     *
     * @param creator the value for ml_third_platform_info.creator
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_third_platform_info.state
     *
     * @return the value of ml_third_platform_info.state
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_third_platform_info.state
     *
     * @param state the value for ml_third_platform_info.state
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}