package com.kxkj.wxpublic.dao.model;

import java.util.Date;

public class UserDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_user.id
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_user.name
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_user.nick
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private String nick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_user.avatar
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private Long avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_user.phone
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_user.desc
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_user.email
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_user.password
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_user.gmt_create
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_user.gmt_modified
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_user.creator
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_user.state
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_user.id
     *
     * @return the value of ml_user.id
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_user.id
     *
     * @param id the value for ml_user.id
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_user.name
     *
     * @return the value of ml_user.name
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_user.name
     *
     * @param name the value for ml_user.name
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_user.nick
     *
     * @return the value of ml_user.nick
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public String getNick() {
        return nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_user.nick
     *
     * @param nick the value for ml_user.nick
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setNick(String nick) {
        this.nick = nick == null ? null : nick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_user.avatar
     *
     * @return the value of ml_user.avatar
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public Long getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_user.avatar
     *
     * @param avatar the value for ml_user.avatar
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setAvatar(Long avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_user.phone
     *
     * @return the value of ml_user.phone
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_user.phone
     *
     * @param phone the value for ml_user.phone
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_user.desc
     *
     * @return the value of ml_user.desc
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_user.desc
     *
     * @param desc the value for ml_user.desc
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_user.email
     *
     * @return the value of ml_user.email
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_user.email
     *
     * @param email the value for ml_user.email
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_user.password
     *
     * @return the value of ml_user.password
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_user.password
     *
     * @param password the value for ml_user.password
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_user.gmt_create
     *
     * @return the value of ml_user.gmt_create
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_user.gmt_create
     *
     * @param gmtCreate the value for ml_user.gmt_create
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_user.gmt_modified
     *
     * @return the value of ml_user.gmt_modified
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_user.gmt_modified
     *
     * @param gmtModified the value for ml_user.gmt_modified
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_user.creator
     *
     * @return the value of ml_user.creator
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_user.creator
     *
     * @param creator the value for ml_user.creator
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_user.state
     *
     * @return the value of ml_user.state
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_user.state
     *
     * @param state the value for ml_user.state
     *
     * @mbggenerated Wed Mar 20 11:58:31 CST 2019
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}